apiVersion: v1
kind: Secret
metadata:
  name: powermax-creds
  namespace: powermax
type: Opaque
data:
  # set username to the base64 encoded username
  username: bm90X3RoZV91c2VybmFtZQ==
  # set password to the base64 encoded password
  password: bm90X3RoZV9wYXNzd29yZA==
  # Uncomment the following key if you wish to use ISCSI CHAP authentication (v1.3.0 onwards)
  # chapsecret: <base64 CHAP secret>
