apiVersion: v1
kind: Secret
metadata:
  name: vcenter-creds
  namespace: powermax
type: Opaque
data:
  # set username to the base64 encoded username of vCenter
  username: bm90X3RoZV91c2VybmFtZQ==
  # set password to the base64 encoded password of vCenter
  password: bm90X3RoZV9wYXNzd29yZA==
