port: 2222
config:
  storageArrays:
    - storageArrayId: "000000000001"
      primaryURL: https://primary-3.unisphe.re:8443
      backupURL: https://backup-3.unisphe.re:8443
      proxyCredentialSecrets:
        - primary-unisphere-secret-1
        - backup-unisphere-secret-1
    - storageArrayId: "000000000002"
      primaryURL: https://primary-4.unisphe.re:8443
      backupURL: https://backup-5.unisphe.re:8443
      proxyCredentialSecrets:
        - primary-unisphere-secret-2
        - backup-unisphere-secret-2
  managementServers:
    - url: https://primary-3.unisphe.re:8443
      arrayCredentialSecret: primary-unisphere-secret-1
      skipCertificateValidation: true
    - url: https://backup-3.unisphe.re:8443
      arrayCredentialSecret: backup-unisphere-secret-1
      skipCertificateValidation: false
      certSecret: "secret-cert"
    - url: https://primary-4.unisphe.re:8443
      arrayCredentialSecret: primary-unisphere-secret-2
      skipCertificateValidation: true
    - url: https://backup-5.unisphe.re:8443
      arrayCredentialSecret: backup-unisphere-secret-2
      skipCertificateValidation: false
      certSecret: "secret-cert"
