port: 2222
config:
  storageArrays:
    - storageArrayId: "000000000001"
      primaryURL: https://primary-3.unisphe.re:8443
      proxyCredentialSecrets:
        - primary-unisphere-secret-1
  managementServers:
    - url: https://primary-3.unisphe.re:8443
      arrayCredentialSecret: primary-unisphere-secret-1
      skipCertificateValidation: true
