# Copyright © 2020-2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

storageArrays:
  - storageArrayId: "000000000001"
    primaryEndpoint: https://primary-1.unisphe.re:8443
    backupEndpoint: https://backup-1.unisphe.re:8443
  - storageArrayId: "000000000002"
    primaryEndpoint: https://primary-2.unisphe.re:8443
    backupEndpoint: https://backup-2.unisphe.re:8443
managementServers:
  - endpoint: https://primary-1.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
  - endpoint: https://backup-1.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: false
  - endpoint: https://primary-2.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
  - endpoint: https://backup-2.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: false
