storageArrays:
  - storageArrayId: "000000000001"
    primaryEndpoint: https://primary-1.unisphe.re:8443
    backupEndpoint: https://backup-1.unisphe.re:8443
  - storageArrayId: "000000000002"
    primaryEndpoint: https://primary-2.unisphe.re:8443
    backupEndpoint: https://backup-2.unisphe.re:8443
managementServers:
  - endpoint: https://primary-1.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
  - endpoint: https://backup-1.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
  - endpoint: https://primary-2.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
  - endpoint: https://backup-2.unisphe.re:8443
    username: admin
    password: password
    skipCertificateValidation: true
