port: "2222"
config:
  storageArrays:
  - storageArrayId: "000000000001"
    primaryEndpoint: https://127.0.0.1:9104/
    backupEndpoint: https://127.0.0.1:9109/
    proxyCredentialSecrets:
    - proxy-secret-1
  managementServers:
  - endpoint: https://127.0.0.1:9104/
    arrayCredentialSecret: proxy-secret-1
    certSecret: cert-secret-4
  - endpoint: https://127.0.0.1:9109/
    arrayCredentialSecret: proxy-secret-1
    certSecret: cert-secret-4
