/*
 *
 * Copyright © 2021-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csi-powermax/v2/pkg/symmetrix (interfaces: RoundTripperInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRoundTripperInterface is a mock of RoundTripperInterface interface.
type MockRoundTripperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRoundTripperInterfaceMockRecorder
}

// MockRoundTripperInterfaceMockRecorder is the mock recorder for MockRoundTripperInterface.
type MockRoundTripperInterfaceMockRecorder struct {
	mock *MockRoundTripperInterface
}

// NewMockRoundTripperInterface creates a new mock instance.
func NewMockRoundTripperInterface(ctrl *gomock.Controller) *MockRoundTripperInterface {
	mock := &MockRoundTripperInterface{ctrl: ctrl}
	mock.recorder = &MockRoundTripperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoundTripperInterface) EXPECT() *MockRoundTripperInterfaceMockRecorder {
	return m.recorder
}

// RoundTrip mocks base method.
func (m *MockRoundTripperInterface) RoundTrip(arg0 *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoundTrip", arg0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoundTrip indicates an expected call of RoundTrip.
func (mr *MockRoundTripperInterfaceMockRecorder) RoundTrip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoundTrip", reflect.TypeOf((*MockRoundTripperInterface)(nil).RoundTrip), arg0)
}
