// Code generated by MockGen. DO NOT EDIT.
// Source: config.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddConfigPath mocks base method.
func (m *MockManager) AddConfigPath(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConfigPath", arg0)
}

// AddConfigPath indicates an expected call of AddConfigPath.
func (mr *MockManagerMockRecorder) AddConfigPath(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConfigPath", reflect.TypeOf((*MockManager)(nil).AddConfigPath), arg0)
}

// GetString mocks base method.
func (m *MockManager) GetString(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockManagerMockRecorder) GetString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockManager)(nil).GetString), arg0)
}

// ReadInConfig mocks base method.
func (m *MockManager) ReadInConfig() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadInConfig")
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadInConfig indicates an expected call of ReadInConfig.
func (mr *MockManagerMockRecorder) ReadInConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadInConfig", reflect.TypeOf((*MockManager)(nil).ReadInConfig))
}

// SetConfigName mocks base method.
func (m *MockManager) SetConfigName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigName", arg0)
}

// SetConfigName indicates an expected call of SetConfigName.
func (mr *MockManagerMockRecorder) SetConfigName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigName", reflect.TypeOf((*MockManager)(nil).SetConfigName), arg0)
}

// SetConfigType mocks base method.
func (m *MockManager) SetConfigType(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigType", arg0)
}

// SetConfigType indicates an expected call of SetConfigType.
func (mr *MockManagerMockRecorder) SetConfigType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigType", reflect.TypeOf((*MockManager)(nil).SetConfigType), arg0)
}
