# This sample manifest file should be used to create VolumeSnapshotClass
# if you have v1 VolumeSnapshotClass CRD installed in your cluster
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: powermax-snapclass
# If using custom driver name, change the following to point to the custom name
driver: csi-powermax.dellemc.com
deletionPolicy: Delete
