# This is a sample manifest for a Storage Class for filesystem type xfs 
# Change instances of <SYMID> to the Local Symmetrix ID of the PowerMax array
# In case you installed the driver with a custom name, then replace all instances of 
# "csi-powermax.dellemc.com" with the custom provisioner name
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powermax-xfs 
parameters:
  FsType: xfs
  SRP: <SRP Name> #Insert SRP name here
  SYMID: <SYMID> #Insert Symmetrix ID
  ServiceLevel: <Service Level> #Insert Service Level Name
provisioner: csi-powermax.dellemc.com
reclaimPolicy: Delete
