# This is a sample manifest for utilizing the replication feature
# Set storage.dell.com/isReplicationEnabled to true to enable replication
# PVCs created using this storage class will be scheduled to any node
# If you want to use Topologies, add the allowedTopologies params

# Change instances of <SYMID> to the Local Symmetrix ID of the PowerMax array
# Changes instances of <RemoteSYMID> to the Remote Symmetrix ID of the PowerMax array
# In case you installed the driver with a custom name, then replace all instances of 
# "csi-powermax.dellemc.com" with the custom provisioner name

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powermax-srdf
parameters:
  SRP: <SRP Name> #Insert SRP name here
  SYMID: <SYMID> #Insert Symmetrix ID
  RemoteSYMID: <RemoteSYMID> #Insert Remote Symmetrix ID
  ServiceLevel: <Service Level> #Insert Service Level Name
  replication.storage.dell.com/isReplicationEnabled: <Enable> #Set this to true to enable replication
  RemoteServiceLevel: <Remote Service Level> #Insert Remote Service Level Name
  RdfMode: <RdfMode> #Insert the SRDF Mode to specify one from: ASYNC, SYNC or METRO
  RdfGroup: <RdfGroup> #Insert the Local SRDF group which protects using Mode mentioned above  
  RemoteRDFGroup: <RemoteRDFGroup> #Insert the Remote SRDF Group which is bound with Local SRDF group
  replication.storage.dell.com/remoteStorageClassName: <RemoteStorageClassName> #Storage class name on remote cluster to create remote PV
  replication.storage.dell.com/remoteClusterID: <RemoteClusterID> # ClusterID to which resources will get replicated
provisioner: csi-powermax.dellemc.com 
reclaimPolicy: Delete
volumeBindingMode: Immediate
