{{ if eq .Values.kubeversion  "v1.13" }}
apiVersion: csi.storage.k8s.io/v1alpha1
{{ else }}
apiVersion: storage.k8s.io/v1beta1
{{ end }} 
kind: CSIDriver
metadata:
    name: powermax
spec:
    attachRequired: true
    podInfoOnMountVersion: "v1"
