apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  {{- if eq .Values.customDriverName.enabled true}}
    name: {{ printf "%s-%s" .Release.Namespace .Values.customDriverName.value }}
  {{- else }}
    name: powermax
  {{- end }}
spec:
    attachRequired: true
