{{- if eq .Values.kubeversion  "v1.20" }}
apiVersion: snapshot.storage.k8s.io/v1
{{- else }}
apiVersion: snapshot.storage.k8s.io/v1beta1
{{- end}}
deletionPolicy: Delete
kind: VolumeSnapshotClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.snapshotClass.name}}
{{- if eq .Values.customDriverName.enabled true}}
driver: {{ printf "%s.%s.dellemc.com" .Release.Namespace .Values.customDriverName.value }}
{{- else }}
driver: csi-powermax.dellemc.com
{{- end }}
