apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.snapshotClass.name}}
{{- if eq .Values.customDriverName.enabled true}}
snapshotter: {{ printf "%s.%s.dellemc.com" .Release.Namespace .Values.customDriverName.value }}
{{- else }}
snapshotter: csi-powermax.dellemc.com
{{- end }}
