apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotclasses.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io 
  version: v1alpha1 
  scope: Cluster
  names: 
    kind: VolumeSnapshotClass
    plural: volumesnapshotclasses
  subresources:
    status: {}

