apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reverseproxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: 2222
  selector:
    name: {{ .Release.Name }}-reverseproxy
  type: ClusterIP
