name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:

  # golang static analysis checks
  go-static-analysis:
    uses: dell/common-github-actions/.github/workflows/go-static-analysis.yaml@main
    name: Golang Validation

  common:
    name: Common github actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependent module gopowermax
        uses: actions/checkout@v4
        with:
          repository: dell/gopowermax
          path: 'gopowermax'
      - name: Quality Checks
        uses: dell/common-github-actions/.github/workflows/go-common.yml@main
